<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Task1.aspx.cs" Inherits="Default2" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>  
    <div class="sqltrack">
            <div style="height: 100px; width: 340px">CREATE TABLE CLIENT(
                <br />&nbsp;&nbsp;&nbsp; 
                ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; INT NOT NULL,
                <br />
        &nbsp;&nbsp;&nbsp; NAME&nbsp; VARCHAR (50) NOT NULL,      
                <br />
        &nbsp;&nbsp;&nbsp; PRIMARY KEY (ID)
                );
            </div>    
    </div>
    <form id="form1" runat="server">
        <div>
            <asp:Button runat="server" OnClick="btnCreate_Click" Text="Create Table" />
        </div>
        <div>
            <h1>Add clients</h1>
            <!--ID could only be number, and the maximum length is 12 -->
            ID:      
         <asp:TextBox ID="id" runat="server" onkeypress="if (event.keyCode < 48 || event.keyCode >57) event.returnValue = false;" 
              MaxLength="12"></asp:TextBox>
            <br />
            <!--the maximum length of name is 50 -->
            Name:   
         <asp:TextBox ID="name" runat="server" MaxLength ="50"></asp:TextBox>
            <br />
            <asp:Button runat="server" OnClick="addNewRow" Text="Add Client" />
        </div>
        <div>
            Your client table now is like:<br />
            <div>
                <asp:GridView runat="server" ID="Gv1" HeaderStyle-BackColor="Red" AutoGenerateDeleteButton="True" CellPadding="4" DataKeyNames="ID" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                    SelectCommand="SELECT * FROM [CLIENT]" 
                    DeleteCommand="DELETE FROM [CLIENT] WHERE id = @ID">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="Gv1" Name="id" PropertyName="SelectedDataKey" />
                    </DeleteParameters>
                </asp:SqlDataSource>
            </div>
        </div>
        <div>
            <br />
            Duplicate Names Are Here:<br />

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource2" CellPadding="4" ForeColor="#333333" GridLines="None" DataKeyNames="Id">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                </Columns>
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [CLIENT] WHERE Name IN (SELECT NAME FROM [CLIENT] GROUP BY Name HAVING COUNT(*)>1 )"></asp:SqlDataSource>
        </div>
    </form>
</body>
</html>